### ISSUE TITLE
SerialPort new version

### ISSUE THREAD

**Issue by GuilhermeCouto** [song940/node-escpos#383]
Hi everybody, I found a problem with printing on Serial ports.

Serialprinter updates and so or file adapter escpos-serialprinter must be updated too.

The error you got is TypeError: SerialPort is not a constructor

Thats because the constructor changed.

I fixed it by changing the line 16 and 17 to 
```js
const { SerialPort } = require('serialport');
this.device = new SerialPort({ path: port, baudRate: 9600, autoOpen: false });
```

If you could change the npm repo I will appreciate.

**Comment by marceloch2** [comment]
Same here. The new version of SerialPort too.

**Comment by ma-zal** [comment]
### Root cause

Library `escpos` has `package.json` dependencies defined without versions:

```json
{
  "optionalDependencies": {
    "serialport": "*",
  }
}
```

And `escpos` is designed for `serialport` version 9. And on 11 Dec 2021 there has been [released `serialport` version 10](https://github.com/serialport/node-serialport/releases), which has some breaking changes.

### Possible workaround

Force `serialport` library version 9.

1) Add to `package.json`:

    ```json
    {
      ... rest of file,
      "resolutions": {
        "escpos/serialport": "9.2.8"
      }
    }
    ```

2) Delete `node_modules` and `yarn.lock`.

3) Install all dependencies again by `yarn`.
